### ISSUE TITLE
Dynamic URL

### ISSUE THREAD

**Issue by distolma** [MatteoGabriele/vue-progressive-image#20] opened 2017-09-03 09:48 UTC
Hi Gabriele, excellent work. It would be better if you add support for dynamical URL. For example i load my background image url from another server, and my default image url it's just empty string. When i received response from another server whit two urls (small and full image) and pass urls to my background component and then to `progressive-background` component, nothing happens. Maybe nothing happens because `vue-progressive-image` load image on `mounted` event of lifecycle hooks. Is it possible to add functional for loading dynamic images url. I think it would be very helpfull.

**Comment by MatteoGabriele** [comment] 2017-09-03 11:21
Hi @distolma thanks for your feedback :)

I have to be honest, I don't really understand your suggestion about the dynamic url.
Yes I load images on mounted because I need the DOM to be ready. There's a trick that allow me to know exactly when the image is loaded and rendered in the browser and I need to use a canvas element and an image tag.

If you could add some code examples of what you mean would be nice

thanks!

**Comment by smarterdigitalltd** [comment] 2017-09-03 15:10
Hello @MatteoGabriele 

I have just found your library, and I *think* I have the same issue as @distolma which is why I am jumping in.

I too have an external API where I get the image URL from.

In my component, on the created() lifecycle hook, I use Axios to get the URL from the API and then set a component data property to the value

```
        created() {
            axios.get(`media/${this.course.course_banner.ID}`)
                .then(response => {
                    this.courseImage = response.data.media_details.sizes['medium'].source_url
                })
        }
```

In my `<progressive-img>` component, I then need to use the courseImage property as the src attribute.

Without progressive-image, it looks like this and works (of course, without loading progressively):

```
<img class="card-img-top" :src="courseImage" />
```

However, if I try and use the `:src` property on a `<progressive-img>` component 

eg. 

```
<progressive-img class="card-img-top" :src="courseImage" />
```

then I get the error:

```
Invalid prop: type check failed for prop "src". Expected String, got Null.
```

If this isn't what you meant @distolma then apologies... ignore me and I will open a new issue. Otherwise, I hope it helps explain :)

**Comment by distolma** [comment] 2017-09-03 15:25
@smarterdigitalltd yes, my issue is similar to your.

@MatteoGabriele i have background image, that i get from unsplash API. Initial state is object with two keys (small and full image) and this set to empty string.
```
{
  smallImage: '',
  fullImage: '',
}
```
When app is `mounted`, `axios` fetch data from unsplash API and `vuex` mutated the initial store.
```
{
  smallImage: 'https://someurl',
  fullImage: 'https://someurl',
}
```
However, when app is mounted, `<progressive-img>` is started to load images. And when component receive a new props, `<progressive-img>` don't load new images.

It will be cool, if your component will watch to the props and reload images when `src` is changed.

**Comment by MatteoGabriele** [comment] 2017-09-03 15:35
Ah ok I got the point! Basically the component is not reactive.
I have little more clear what you guys mean. I'll see what I can do.

thanks for your feedback :)

**Comment by smarterdigitalltd** [comment] 2017-09-03 18:14
Thank you too @MatteoGabriele! 👍

**Comment by MatteoGabriele** [comment] 2017-09-14 13:42
Sorry for the late fix, I was busy as hell! 😄 
published with vue-progressive-image@2.1.4

let me know if it works as expected!

thanks again for your feedback

**Comment by distolma** [comment] 2017-09-14 18:53
Hi, thanks for fix.
it almost works, but has some bug. VPI worked perfectly when mounted first time. Small and full images are correct.

![image](https://user-images.githubusercontent.com/16022556/30447303-4d822832-9994-11e7-9f97-bd553436143f.png)

but when component receives new `src` small image updates, but full image remains the same
![image](https://user-images.githubusercontent.com/16022556/30447483-f58d21d0-9994-11e7-94c1-0d51aca51f96.png)

I carried out some code review and noticed that part of `if statement` is reason why full image doesn't update
![image](https://user-images.githubusercontent.com/16022556/30447606-58abe602-9995-11e7-8e0f-7368e90d90d0.png)

if i delete that part of code, the component will start working without bugs, but 'some canvas error' will appear in Console 
![image](https://user-images.githubusercontent.com/16022556/30447953-15db96aa-9996-11e7-9514-ef11c48e60fd.png)

Hope this information will help you.

**Comment by MatteoGabriele** [comment] 2017-09-14 19:03
@distolma I can't see the images you posted, there's a server error

**Comment by MatteoGabriele** [comment] 2017-09-14 19:05
@distolma but would be nice if you could make a repository that I can take a lot at. With a reproduction of these errors I can probably fix it way easier.

thanks

**Comment by distolma** [comment] 2017-09-14 19:35
@MatteoGabriele https://github.com/distolma/vue-issue

**Comment by MatteoGabriele** [comment] 2017-09-15 08:14
I think I've fixed it this time! :)
thanks a lot for your feedback

see vue-progressive-image@2.1.5

I'll wait your feedback before closing the ticket again

**Comment by distolma** [comment] 2017-09-15 12:39
Thanks, the component works good. 🎉

**Comment by MatteoGabriele** [comment] 2017-09-15 12:42
@distolma nice!

thanks again :)

**Closed as completed by MatteoGabriele** 2017-09-15 12:42 UTC
Labels: bug

**Comment by johncloud200** [comment] 2017-11-18 10:09
Hi Q(^_^)Q
I have similar case also

```:src="await.img.from.api"```

it works, but when I add the fallback

```fallback="//example.com/image.jpg"```

always show **fallback** instead of **src**

any one know how to fix?

**Comment by MatteoGabriele** [comment] 2017-11-18 11:00
Be sure that the image you are binding is working properly otherwise I'll suggest you to create a small repository describing the error that you have so that I can have a look.

Cheers
