### ISSUE TITLE
Maybe a bug in mobile safari?

### ISSUE THREAD

**Issue by rchrdnsh** [MatteoGabriele/vue-progressive-image#24] opened 2017-09-28 19:53 UTC
### Description

I am noticing an issue that seems to effect mobile safari. I have a nested .vue component with named slots that is being used in a v-for loop to loop through an array of objects. When I use the normal `<img>` tag in the loop everything works as expected. When I use the `<progressive-background>` tag the text that is over-layed on top the image disappears on subsequent iterations through the loop, while it does not on the plain `<img>` tag version.

### Expected behavior

The over-layed text should appear above every iteration through the array of objects of data. It works fine on desktop Safari, but not on mobile Safari.

### Actual behavior

The over-layed text disappears on every subsequent iteration through the data.

### Environment

vue-progressive-image@2.1.3

1. Operating system:

macOS 10.12.6
iOS 11.0.1

2. Browser and version:

Desktop Safari - 11.0
Mobile Safari - The latest (don't know how to find out the exact version number)

### Reproducible Demo

www.arrowgtp.com

So I have simply copied the component so that it loops through the data twice. The first loop is with the regular `<img>` tag and the second loop is with the `<progressive-background>` tag. On desktop Safari it renders properly through both loops, but on mobile Safari it does not render the over-layed text in the second loop, which is using `<progressive-background>` instead of `<img>`...everything else is the same, as far as I can tell... 

I hope this all makes sense and you see the issue that is occurring...I don't have an android device, so I have not tested it yet on mobile android...will try to do so in the near future :-)

Thanks @MatteoGabriele :-)

**Comment by MatteoGabriele** [comment] 2017-09-28 20:24
hey @rchrdnsh 
I'm sorry but I have to ask you a fair reproduction: a simple application with your issue.
Just looking at it this could literally be everything with big chance of just some of your application style making some weird glitch.

**Comment by MatteoGabriele** [comment] 2017-09-29 14:09
I just tested other browsers and it works.
First Chrome, middle one is Safari and the last one is Safari in iphoneX (ios11)

![screen recording 2017-09-29 at 04 06 pm](https://user-images.githubusercontent.com/5337152/31019552-4ee932fe-a530-11e7-80a7-b881a2bab8fa.gif)

It's probably due to some CSS in your application.
Let me know if you find a way to reproduce the error, for now I'm going to close it.

Thanks again for your feedback :)

**Closed as completed by MatteoGabriele** 2017-09-29 14:09 UTC
Labels: reproduction needed

**Comment by rchrdnsh** [comment] 2017-10-01 01:35
ok, I'll try to create a simple reproduction of the issue to help you out :-)
