### ISSUE TITLE
Adding IMPORT causes blank page

### ISSUE THREAD

**Issue by wutmikee** [MatteoGabriele/vue-progressive-image#38] opened 2018-01-22 04:52 UTC
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Description

When I try adding, `import VueProgressiveImage from 'vue-progressive-image'` to my app.js file, in my Laravel project, the compiling the app returns a blank page. I remove the import, and my app loads as expected. Can figure out the issue!?

### Environment

Run this command in the project folder and fill in the result:

`npm ls vue-progressive-image`: vue-progressive-image@2.4.2

Then, specify:

1. Operating system: Mac OSX
2. Browser and version: Safari/Chrome (Latest)

**Comment by MatteoGabriele** [comment] 2018-01-22 08:38
hi @mbarwick83 
thanks for your feedback, it's very strange but I'll have a check asap.

**Comment by MatteoGabriele** [comment] 2018-01-22 15:42
I really don't have this issue, but if you could try with the new build vue-progressive-image@2.4.3 would be great.
There were some problems during deploy of the 2.4.2 and so now also this issue could be fixed.

if it doesn't I suggest you to make a simple reproduction of you error and please also specify which OS version and browser version

thanks

**Comment by wutmikee** [comment] 2018-01-22 16:04
Negative. New version does not work. It's a bit hard for me to reproduce the error, especially online for you to view. It's a Laravel build, using Laravel Mix to compile assets. An environment would need to be set up.

macOS High Sierra / Safari Version 11.0.3 OR Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by MatteoGabriele** [comment] 2018-01-22 16:23
The reproduction its useful for this cases in specific. Because everyone has a specific environment, use case or way of compiling, if the error cannot be reproduced alone, I can't help and it might be "your fault".

Please take your time to create a simple riproduction outside your project or I have to close this issue

Thanks for your feedback

**Comment by wutmikee** [comment] 2018-01-22 16:33
Sure, let me try and put something together for you.

**Comment by wutmikee** [comment] 2018-01-22 17:55
Okay, I build out a new Laravel/Vue project, and the issue is not there. Hmm. has to be something on my end. Fukkkkkk.  You an close this issue. Ps; if you have any tips on what it could be, please let me know!

**Comment by MatteoGabriele** [comment] 2018-01-22 20:46
No I'm sorry.
I usually keep frontend and backend separated as mush as I can. Don't know much about Laravel and Laravel Mix

good luck! :)

**Closed as completed by MatteoGabriele** 2018-01-22 20:46 UTC
Labels: reproduction needed

**Comment by wutmikee** [comment] 2018-01-23 01:20
Thanks...looks like there's a dependancy conflict...which one, who knows. Thanks for your help - and great package btw!
